import { test, expect } from '@playwright/test'

test('create, instrument, investigate, export, restore and sign out on desktop and mobile', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await page.getByLabel('Project name').fill(`Browser test ${Date.now()}`)
  await page.getByLabel('Website domain').fill('app.test')
  await page.getByRole('button', { name: 'Create project', exact: true }).last().click()
  await expect(page.getByText('Save your keys before continuing')).toBeVisible()
  const inputs = await page.locator('input[readonly]').evaluateAll(elements => elements.map(element => (element as HTMLInputElement).value))
  const [tracking, read, management] = inputs
  expect(tracking).toMatch(/^alw_/); expect(read).toMatch(/^alr_/); expect(management).toMatch(/^alm_/)
  await page.getByRole('button', { name: 'Continue to installation' }).click()
  await expect(page.getByText('Private management access')).toBeVisible()
  const ingest = await request.post('http://127.0.0.1:8010/api/v1/ingest', {
    headers: { 'X-Write-Key': tracking }, data: { events: [
      { name: 'pageview', visitor_id: 'v1', session_id: 's1', url: 'https://app.test/pricing' },
      { name: 'signup', visitor_id: 'v1', session_id: 's1' },
      { name: 'revenue', visitor_id: 'v1', revenue_amount: 49, revenue_currency: 'USD' },
    ] },
  }); expect(ingest.ok()).toBeTruthy()
  await page.getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(page.getByText('Compared with the previous period')).toBeVisible()
  await expect(page.getByText('$49.00').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/overview-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Goals', exact: true }).click()
  await page.getByLabel('Goal name', { exact: true }).fill('Account signup')
  await page.getByLabel('Tracked event name', { exact: true }).fill('signup')
  await page.getByRole('button', { name: 'Create goal', exact: true }).click()
  await expect(page.getByText('1 converted / 1 visitors with a pageview')).toBeVisible()
  await page.getByRole('button', { name: 'Investigations', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'What changed—and where?' })).toBeVisible()
  await page.getByLabel('Investigation title').fill('Signup launch check')
  await page.getByRole('button', { name: 'Save evidence', exact: true }).click()
  await expect(page.getByText('Evidence saved. This record will stay unchanged when new events arrive.')).toBeVisible()
  await page.getByLabel('Review status').selectOption('resolved')
  await page.getByLabel('Decision and supporting context').fill('Tracking and signup verified.')
  await page.getByRole('button', { name: 'Save review', exact: true }).click()
  await expect(page.getByText('Review saved. Evidence is unchanged.')).toBeVisible()
  const evidenceDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export evidence', exact: true }).click()
  expect((await evidenceDownload).suggestedFilename()).toBe('metricairn-investigation.json')
  await page.screenshot({ path: 'test-results/investigation-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Retention', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Do visitors come back?' })).toBeVisible()
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await page.getByLabel('Traffic, conversion, or revenue question').fill('Where is revenue coming from?')
  await page.getByRole('button', { name: 'Ask question' }).click()
  await expect(page.getByText(/Top revenue source/)).toBeVisible()
  await page.getByRole('button', { name: 'Save question', exact: true }).click()
  await expect(page.getByText('Saved questions')).toBeVisible()
  await page.getByText(/Inspect evidence/).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('metricairn-answer.csv')
  await page.screenshot({ path: 'test-results/ask-desktop.png', fullPage: true })
  for (const name of ['Realtime', 'Events', 'Revenue', 'Funnels', 'Alerts', 'Agent usage', 'Settings', 'Goals', 'Retention', 'Investigations']) {
    await page.getByRole('button', { name, exact: true }).click()
    await expect(page.locator('h1')).toBeVisible()
    await expect(page.locator('h1')).toHaveText(new RegExp(name, 'i'))
  }
  await page.reload()
  await expect(page.getByRole('button', { name: 'Sign out' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Overview', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/overview-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByLabel('Private read key')).toBeVisible()
  expect(await page.evaluate(() => sessionStorage.getItem('metricairn_management_key'))).toBeNull()
  expect(errors).toEqual([])
})

test('invalid login and unseeded demo surface an actionable error', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Private read key').fill('alr_invalid')
  await page.getByRole('button', { name: 'Connect', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Read access denied')
  await page.getByRole('button', { name: /Explore the simulated/ }).click()
  await expect(page).toHaveURL(/\?demo=billwise/)
  await expect(page.getByRole('heading', { name: 'How Maya investigates growth at Billwise.' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('demo data is unavailable')
  await expect(page.getByText(/verified customer savings/)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'How Maya investigates growth at Billwise.' })).toBeVisible()
})
